[project]
name = "minimal-agent"
created = "2025-11-04T15:23:15.075584"
framework_version = "0.3.7"

[cli]
version = "1.0.0"
command = "co init"
template = "none"

[agent]
address = "0x3b9fd603fa7fd31f31f9087985133cc54f11ae2ed0524e5627efe4e59cbbbd5f"
short_address = "0x3b9f...bd5f"
email = "0x3b9fd603@mail.openonion.ai"
email_active = true
created_at = "2025-11-04T15:23:15.075599"
algorithm = "ed25519"
default_model = "gpt-4o-mini"
max_iterations = 10
